"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.Test__factory = exports.Swapper__factory = exports.Multicall__factory = exports.Lock__factory = exports.IntegrationUniswapV3__factory = exports.IntegrationUniswapV2__factory = exports.IntegrationBalancer__factory = exports.ArbRoleManager__factory = exports.ArbMoneyManager__factory = exports.integrationKyberClassicSol = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.integrationKyberClassicSol = __importStar(require("./IntegrationKyberClassic.sol"));
var ArbMoneyManager__factory_1 = require("./ArbMoneyManager__factory");
Object.defineProperty(exports, "ArbMoneyManager__factory", { enumerable: true, get: function () { return ArbMoneyManager__factory_1.ArbMoneyManager__factory; } });
var ArbRoleManager__factory_1 = require("./ArbRoleManager__factory");
Object.defineProperty(exports, "ArbRoleManager__factory", { enumerable: true, get: function () { return ArbRoleManager__factory_1.ArbRoleManager__factory; } });
var IntegrationBalancer__factory_1 = require("./IntegrationBalancer__factory");
Object.defineProperty(exports, "IntegrationBalancer__factory", { enumerable: true, get: function () { return IntegrationBalancer__factory_1.IntegrationBalancer__factory; } });
var IntegrationUniswapV2__factory_1 = require("./IntegrationUniswapV2__factory");
Object.defineProperty(exports, "IntegrationUniswapV2__factory", { enumerable: true, get: function () { return IntegrationUniswapV2__factory_1.IntegrationUniswapV2__factory; } });
var IntegrationUniswapV3__factory_1 = require("./IntegrationUniswapV3__factory");
Object.defineProperty(exports, "IntegrationUniswapV3__factory", { enumerable: true, get: function () { return IntegrationUniswapV3__factory_1.IntegrationUniswapV3__factory; } });
var Lock__factory_1 = require("./Lock__factory");
Object.defineProperty(exports, "Lock__factory", { enumerable: true, get: function () { return Lock__factory_1.Lock__factory; } });
var Multicall__factory_1 = require("./Multicall__factory");
Object.defineProperty(exports, "Multicall__factory", { enumerable: true, get: function () { return Multicall__factory_1.Multicall__factory; } });
var Swapper__factory_1 = require("./Swapper__factory");
Object.defineProperty(exports, "Swapper__factory", { enumerable: true, get: function () { return Swapper__factory_1.Swapper__factory; } });
var Test__factory_1 = require("./Test__factory");
Object.defineProperty(exports, "Test__factory", { enumerable: true, get: function () { return Test__factory_1.Test__factory; } });
