"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Swapper__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
    {
        inputs: [
            {
                internalType: "address",
                name: "_router",
                type: "address",
            },
            {
                internalType: "uint256",
                name: "_amtIn",
                type: "uint256",
            },
            {
                internalType: "address[]",
                name: "_poolPath",
                type: "address[]",
            },
            {
                internalType: "contract IERC20[]",
                name: "_tokenPath",
                type: "address[]",
            },
        ],
        name: "getAmountOutMinKyberClassic",
        outputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "address",
                name: "router",
                type: "address",
            },
            {
                internalType: "address[]",
                name: "path",
                type: "address[]",
            },
            {
                internalType: "uint256",
                name: "amtIn",
                type: "uint256",
            },
        ],
        name: "getAmountOutMinUniswapV2",
        outputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "swapERC20",
        outputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256",
            },
        ],
        stateMutability: "nonpayable",
        type: "function",
    },
];
class Swapper__factory {
    static createInterface() {
        return new ethers_1.Interface(_abi);
    }
    static connect(address, runner) {
        return new ethers_1.Contract(address, _abi, runner);
    }
}
exports.Swapper__factory = Swapper__factory;
Swapper__factory.abi = _abi;
