/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IDMMExchangeRouter,
  IDMMExchangeRouterInterface,
} from "../../../contracts/IntegrationKyberClassic.sol/IDMMExchangeRouter";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amountIn",
        type: "uint256",
      },
      {
        internalType: "address[]",
        name: "poolsPath",
        type: "address[]",
      },
      {
        internalType: "contract IERC20[]",
        name: "path",
        type: "address[]",
      },
    ],
    name: "getAmountsOut",
    outputs: [
      {
        internalType: "uint256[]",
        name: "amounts",
        type: "uint256[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amountIn",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amountOutMin",
        type: "uint256",
      },
      {
        internalType: "address[]",
        name: "poolsPath",
        type: "address[]",
      },
      {
        internalType: "contract IERC20[]",
        name: "path",
        type: "address[]",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "deadline",
        type: "uint256",
      },
    ],
    name: "swapExactTokensForTokens",
    outputs: [
      {
        internalType: "uint256[]",
        name: "amounts",
        type: "uint256[]",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IDMMExchangeRouter__factory {
  static readonly abi = _abi;
  static createInterface(): IDMMExchangeRouterInterface {
    return new Interface(_abi) as IDMMExchangeRouterInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IDMMExchangeRouter {
    return new Contract(address, _abi, runner) as unknown as IDMMExchangeRouter;
  }
}
