"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IntegrationKyberClassic__factory = exports.IDMMExchangeRouter__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var IDMMExchangeRouter__factory_1 = require("./IDMMExchangeRouter__factory");
Object.defineProperty(exports, "IDMMExchangeRouter__factory", { enumerable: true, get: function () { return IDMMExchangeRouter__factory_1.IDMMExchangeRouter__factory; } });
var IntegrationKyberClassic__factory_1 = require("./IntegrationKyberClassic__factory");
Object.defineProperty(exports, "IntegrationKyberClassic__factory", { enumerable: true, get: function () { return IntegrationKyberClassic__factory_1.IntegrationKyberClassic__factory; } });
