/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IntegrationKyberClassicInterface extends Interface {
  getFunction(nameOrSignature: "getAmountOutMinKyberClassic"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getAmountOutMinKyberClassic",
    values: [AddressLike, BigNumberish, AddressLike[], AddressLike[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAmountOutMinKyberClassic",
    data: BytesLike
  ): Result;
}

export interface IntegrationKyberClassic extends BaseContract {
  connect(runner?: ContractRunner | null): IntegrationKyberClassic;
  waitForDeployment(): Promise<this>;

  interface: IntegrationKyberClassicInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAmountOutMinKyberClassic: TypedContractMethod<
    [
      _router: AddressLike,
      _amtIn: BigNumberish,
      _poolPath: AddressLike[],
      _tokenPath: AddressLike[]
    ],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAmountOutMinKyberClassic"
  ): TypedContractMethod<
    [
      _router: AddressLike,
      _amtIn: BigNumberish,
      _poolPath: AddressLike[],
      _tokenPath: AddressLike[]
    ],
    [bigint],
    "view"
  >;

  filters: {};
}
