/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as integrationKyberClassicSol from "./IntegrationKyberClassic.sol";
export type { integrationKyberClassicSol };
export type { ArbMoneyManager } from "./ArbMoneyManager";
export type { ArbRoleManager } from "./ArbRoleManager";
export type { IntegrationBalancer } from "./IntegrationBalancer";
export type { IntegrationUniswapV2 } from "./IntegrationUniswapV2";
export type { IntegrationUniswapV3 } from "./IntegrationUniswapV3";
export type { Lock } from "./Lock";
export type { Swapper } from "./Swapper";
export type { Test } from "./Test";
